### ISSUE TITLE
Upgrade to Mithril 2

### ISSUE THREAD

**Issue by Cheehau0659** [LegumeFederation/cmap-js#125]
https://mithril.js.org/changelog.html

**Comment by That-Thing** [comment]
The `deserialize` function in `src/model/DataSourceModel.js` returns an error which prevents cmap-js from loading further due to the `data` argument being null (papaparse receives a null object and throws and error).  
This is somehow an issue with the 2.2.2 version of Mithril, and is most likely caused by a change in the `m.request` function.

**Comment by That-Thing** [comment]
[Update branch](https://github.com/LegumeFederation/cmap-js/tree/Mithril-2-update) currently works fine save for a weird issue that stops the rendering at some point until the user clicks or drags something. 

Issues fixed:
- Color picker not working
- Title bar component not dragging properly
- The actual title not dragging with the rest of the data

**Comment by That-Thing** [comment]
Done.
