### ISSUE TITLE
Missing GWAS QTL data on all GmGWAS map

### ISSUE THREAD

**Issue by jd-campbell** [LegumeFederation/cmap-js#140]
@StevenCannon-USDA @That-Thing @nathanweeks 

Looking over the maps on SB-dev the GWAS QTLs are missing on all chromosomes. Note there are no GWAS QTL visible yet the title says "All QTL"   Is this a config file issue or javascript code bug?  An example link is shown below. 

Link to Map 02: https://dev.soybase.org/maps/cmap-all/?config=map-02.json%20

Contact @maxglycine for more details about this issue.

**Comment by nathanweeks** [comment]
This appears to be a configuration issue. The cmap-js instance at the above URL references a config:
https://raw.githubusercontent.com/LegumeFederation/cmap-js/soy-test/config/gm_gwas.json
that filters on a subset of the types present in the feature_type_acc column in the CMap file: https://raw.githubusercontent.com/LegumeFederation/cmap-js/soy-test/data/Soybean-GmGWAS.cmap

specifically:
https://github.com/LegumeFederation/cmap-js/blob/9d012299c36c3bae0cbf8a4f2beaff9419d38f3f/config/gm_gwas.json#L23

I'll go ahead and close this issue here, since there doesn't appear to be an issue with cmap-js per se.

**Comment by maxglycine** [comment]
Well should this go to @That-Thing to change the configuration file?

**Comment by StevenCannon-USDA** [comment]
@maxglycine - Since this pertains to the biology that we want to display, I think it falls to us. May need to set up a meeting to go over the config structure - though as I recall, it's pretty transparent.
