### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by ekcannon** [LegumeFederation/cmap-js#50]
Browser: Chrome 59.0.3071.115, Mac OS X 10.11.6

Scrolling is inconsistent. Sometimes works perfectly, sometimes not.

This page (**https://legumefederation.org/cmap-js/**) opens with the blue bar on the right not spanning the full length and can't be moved. A fragment of it shows at the top. Looks like it may be simply miss-placed.

After zooming in, the view can be scrolled via the blue bar, but can't be scrolled to the bottom and appears to scroll off the top (feature bars are drawn over the coordinates at the top). Repeated efforts to scroll to top or bottom moves the view off the screen and can't get it centered without reloading page.

Managed to get display into a state where mouse position appears to be interpreted ~20-30 pixels to the right, but can't duplicate.

Entry page with immovable blue scroll bar:
<img width="336" alt="screen shot 2017-07-18 at 2 46 47 pm" src="https://user-images.githubusercontent.com/3409057/28336549-036d0cd4-6bc8-11e7-9daa-1d3ee8a3d443.png">

**Comment by adf-ncgr** [comment]
I think what you're seeing is probably due to the fact that the soybase 
map has negative coordinates caused by these markers:

GmComposite2003_A1	A1	-36.1	104.58	GmComposite2003_A1_ss107921684	ss107921684		-36.1	-36.1	SNP	0
GmComposite2003_A1	A1	-36.1	104.58	GmComposite2003_A1_ss107919814	ss107919814		-18.56	-18.56	SNP	0

I guess we need to more gracefully handle this case.

**Comment by awilkey** [comment]
Non-zero start coordinates have been patched with https://github.com/LegumeFederation/cmap-js/commit/e5a57534ff452cb966ded81da57e41a0378474a8 It should work fine now.
